### PR TITLE
custom model create check to avoid configuration error 

### PR DESCRIPTION
**Pull request by derluke**
As outlined in https://datarobot.slack.com/archives/C067KF6USDT/p1714039022065149 custom inference models require a target name

### CODE REVIEW

**Comment by derluke** [comment]
@brau0300 Have another look now. It's a lot simpler. The checks I started to implement are already in the SDK

**Review by brau0300 — APPROVED** [review]
hey Lukas can you confirm this works with `datarobot` on pypi (e.g. doesn't depend on a pre-release or early access?); if it doesn't i suggest we merge after 3.4 drops (hopefully very soon)

**Comment by derluke** [comment]
I can confirm that it does NOT work with 3.3.2 :(

**Comment by brau0300** [comment]
@derluke - got it, sounds like 3.4 was scheduled to be published today so we can keep an eye on that; e.g. important that when we pin a template to an idp release with this change, we also need to update the `datarobot` pin the template to be >3.4 otherwise it will break the template

**Comment by derluke** [comment]
looks like everything is working with the new version of the code
uising datarobot 3.4.0, and community datarobotx-idp v0.2.1

tests were successful

**Comment by brau0300** [comment]
merge away whenever you want!

**Pull request merged**
