### PR TITLE
Update vector_databases.py

### PR DESCRIPTION
**Pull request by derluke**
Using the get_or_create_vector_database helper can throw: 
       
```
datarobot.errors.ClientError: 422 client error: {'detail': 'Vector database execution status must be COMPLETED to create an LLM blueprint'}
```

Adding a little waiting loop

### CODE REVIEW

**Review by mpkrass7 — CHANGES_REQUESTED** [review]
If there's a status it can arrive at that isn't 'completed' (e.g. user feed in an error), this function will run forever. I suggest instead calling `_find_existing_vector_database(` on the result here

**Comment by derluke** [comment]
Very good point

**Comment by brau0300** [comment]
the problem with calling _find_existing again; is it will raise the ERROR case in a way that is confusing to the user vs. making clear it's because the creation errored i would suggest pulling out the polling logic into a _wait_for_creation() function that can be reused in both places and have it properly raise a different error if the completion status is error; that way find_existing can catch the error and instead raise key error whereas the create new case will propagate the error upon creating

**Comment by derluke** [comment]
I've added a waiter - lmk if this is what you had in mind

I would say that if the VDB returns with error it should always raise an error, since idempotency would predict it'll error again with same inputs

**Review by brau0300 — APPROVED** [review]
lgtm

**Review by mpkrass7 — APPROVED** [review]

**Pull request merged**
