### PR TITLE
adding new method to create custom model version from previous version

### PR DESCRIPTION
**Pull request by derluke**

### CODE REVIEW

**Review by mpkrass7 — APPROVED** [review]
LGTM - This makes the unit test a little bit long but I don't see a better place to put it

**Comment by mpkrass7** [comment]
@brau0300 I approved this but figured I'd add you for visibility. This PR lets users increment a custom model version without uploading new files. I don't see a problem with the idea

**Comment by brau0300** [comment]
this is great stuff Lukas - thanks for turning around so quick; i wanna to take a closer look tomorrow AM at the runtime params/dependency build cases before we merge at the runtime will keep you both posted

**Review by brau0300 — APPROVED** [review]

**Review by derluke — COMMENTED** [review]
much cleaner

**Pull request merged**
